
# PYTHON JINJA2 TEMPLATES
keydb: &KEYDB keydb.j2
mongo: &MONGO mongo.j2
volumes: &VOLUMES volumes.j2
service: &SERVICES services.j2
networks: &NETWORKS networks.j2
msg-gateway: &MSG_GATEWAY msg-gateway.j2
pst-gateway: &PST_GATEWAY pst-gateway.j2
redisInsight: &REDIS_INSIGHT redis-insight.j2

# SYSTEM ENVIRONMENT VARIABLES
useRedisInsight: &USE_REDIS_INSIGHT $USE_REDIS_INSIGHT

source:
  template_dir: .templates
  outputs: compose.yml
  env_files:
    - .env
    - apps/msg-gateway/.env
    - apps/pst-gateway/.env

compose:
  - template: *SERVICES

  - template: *MSG_GATEWAY
    depends_on:
      - *KEYDB

  - template: *PST_GATEWAY
    depends_on:
      - *KEYDB
      - *MONGO
      - *MSG_GATEWAY

  - template: *REDIS_INSIGHT
    depends_on:
      - *KEYDB
      - *USE_REDIS_INSIGHT

  - template: *MONGO
  - template: *KEYDB
  - template: *VOLUMES
  - template: *NETWORKS