export const BULLMQ_DEFAULT = Object.freeze({
  TOPIC: 'TOPIC',
  THREAD: 'THREAD',
  PERSIST: 'PERSIST',
  PERSIST_TOPIC: 'PERSIST_TOPIC',
  PERSIST_THREAD: 'PERSIST_THREAD',
  PERSIST_MESSAGE: 'PERSIST_MESSAGE',
} as const);
