export const BULLMQ_DEFAULT = Object.freeze({
  TOPIC: 'TOPIC',
  THREAD: 'THREAD',
  PERSIST: 'PERSIST',
  PERSIST_TOPICS: 'PERSIST_TOPICS',
  PERSIST_THREADS: 'PERSIST_THREADS',
  PERSIST_POSTS: 'PERSIST_POSTS',
} as const);
