export const BULLMQ_JOB = Object.freeze({
  DISPATCH: 'DISPATCH',
  PERSIST: 'PERSIST',
  VECTORIZE: 'VECTORIZE',
} as const);

export const BULLMQ_QUEUE = Object.freeze({
  PERSIST_POST: 'PERSIST_POST',
  PERSIST_TOPIC: 'PERSIST_TOPIC',
  PERSIST_THREAD: 'PERSIST_THREAD',
  BROADCAST_TOPIC: 'BROADCAST_TOPIC',
  VECTORIZE_TOPIC: 'VECTORIZE_TOPIC',
} as const);
