export const BULLMQ_JOB = Object.freeze({
  DISPATCH: 'DISPATCH',
  PERSIST: 'PERSIST',
  VECTORIZE: 'VECTORIZE',
  VISIONS: 'VISIONS',
} as const);

export const BULLMQ_QUEUE = Object.freeze({
  PERSIST_POST: 'PERSIST_POST',
  PERSIST_TOPIC: 'PERSIST_TOPIC',
  PERSIST_THREAD: 'PERSIST_THREAD',
  BROADCAST_POST: 'BROADCAST_POST',
  BROADCAST_TOPIC: 'BROADCAST_TOPIC',
  BROADCAST_THREAD: 'BROADCAST_THREAD',
  VECTORIZE_POST: 'VECTORIZE_POST',
  VECTORIZE_TOPIC: 'VECTORIZE_TOPIC',
  VECTORIZE_THREAD: 'VECTORIZE_THREAD',
  VISIONS_DESCRIBE: 'VISIONS_DESCRIBE',
  VISIONS_COMPARE: 'VISIONS_COMPARE',
  VISIONS_OCR: 'VISIONS_OCR',
} as const);
