export const BULLMQ_JOB = Object.freeze({
  DISPATCH: 'DISPATCH',
  PERSIST: 'PERSIST',
  VECTORIZE: 'VECTORIZE',
  DESCRIBE_IMAGE: 'DESCRIBE_IMAGE',
  COMPARE_IMAGES: 'COMPARE_IMAGES',
  OCR_IMAGE: 'OCR_IMAGE',
} as const);

export const BULLMQ_QUEUE = Object.freeze({
  PERSIST_POST: 'PERSIST_POST',
  PERSIST_TOPIC: 'PERSIST_TOPIC',
  PERSIST_THREAD: 'PERSIST_THREAD',
  BROADCAST_POST: 'BROADCAST_POST',
  BROADCAST_TOPIC: 'BROADCAST_TOPIC',
  BROADCAST_THREAD: 'BROADCAST_THREAD',
  VECTORIZE_POST: 'VECTORIZE_POST',
  VECTORIZE_TOPIC: 'VECTORIZE_TOPIC',
  VECTORIZE_THREAD: 'VECTORIZE_THREAD',
  IMAGE_DESCRIBE: 'IMAGE_DESCRIBE',
  IMAGE_COMPARE: 'IMAGE_COMPARE',
  IMAGE_OCR: 'IMAGE_OCR',
} as const);
