export const BULLMQ_DEFAULT = Object.freeze({
  MESSAGE: 'MESSAGE',
  VECTORIZE: 'VECTORIZE',
  PERSIST: 'PERSIST',
  PERSIST_TOPIC: 'PERSIST_TOPIC',
  PERSIST_THREAD: 'PERSIST_THREAD',
  PERSIST_MESSAGE: 'PERSIST_MESSAGE',
  BROADCAST_MESSAGE: 'BROADCAST_MESSAGE',
  VECTORIZE_MESSAGE: 'VECTORIZE_MESSAGE',
} as const);
